### ISSUE TITLE
Update Spoke and Route Table Module

### ISSUE THREAD

**Issue by jk-ans** [ans-coe/terraform-modules#98]
## Tasks

Updating the spoke module to use the route-table module and to use the subnet association feature in the nsg module

- [x]  Use route-table module
- [x]  Use nsg module subnet association
- [x]  Update validataion in subnet and route table modules
- [x]  Add Advanced Example to spoke module

## Specifications

  - Module/Configuration: spoke 
  - Platform: azure
